apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iam-key-sync.fullname" . }}-secret
  labels:
    {{- include "iam-key-sync.labels" . | nindent 4 }}
type: Opaque
stringData:
  BROKER_JWT: {{ .Values.secret.brokerJwt | quote }}
  BROKER_URL: {{ .Values.secret.brokerUrl | quote }}
  VAULT_URL: {{ .Values.secret.vaultUrl | quote }}
  SYNC_URL: {{ .Values.secret.syncUrl | quote }}
